# copied from official wiki
# https://github.com/mojombo/jekyll/wiki/Configuration

safe:        false
auto:        false
server:      false
server_port: 4000
baseurl:    /blog/
url: http://takazudo.github.com

source:      ./jekyll
destination: ../blog
plugins:     ./jekyll/_plugins

future:      true
lsi:         false
pygments:    false
markdown:    maruku

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

rdiscount:
  extensions: []

kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false
  
  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style

# For more see: https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /entry/:year-:month-:day-:title.html

# all variables can be refered in templates
author : Takazudo
author_full : '"Takazudo" Takeshi Takatsudo'
basedir:    /blog
title: Takazudolog
description: "Takazudo's blog on GitHub"
twitterid: Takazudo
iconurl: http://www.gravatar.com/avatar/a88cc23988f41bba5503dd0bd8ff7750.png?s=48
mail: takazudo@gmail.com

# ignore these
exclude: [".gitignore", "readme.md"]
